name: Setup, build, test and deploy

on:
  push:
    branches: [master]

env:
  REGISTRY: harbor-ingress-tailscale.tail11c31.ts.net
  IMAGE_PROJECT: library
  IMAGE_NAME: apachas-backend
  IMAGE_ARCH: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      # Workaround for https://github.com/tailscale/github-action/issues/108
      - name: Build DNS resolutions
        id: build_hosts_resolutions
        run: |
          registry_ip=$(sudo dig +short ${{ env.REGISTRY }})
          echo "hosts=${{ env.REGISTRY }}:$registry_ip" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-config-inline: |
            [dns]
              nameservers=["100.100.100.100"]
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Get app version
        id: get_version
        run: |
          version=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "::set-output name=version::${version}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          add-hosts: ${{ steps.build_hosts_resolutions.outputs.hosts }}
          platforms: ${{ env.IMAGE_ARCH }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PROJECT }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PROJECT }}/${{ env.IMAGE_NAME }}:latest
