name: Setup, build, test and deploy

on:
  push:
    branches: [master]

env:
  REGISTRY: harbor.jamezrin.name
  IMAGE_PROJECT: apachas
  IMAGE_NAME: apachas-backend
  IMAGE_ARCH: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to my Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Build image
        run: |
          version=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          
          image_name=${REGISTRY}/${IMAGE_PROJECT}/${IMAGE_NAME}
          
          docker buildx build --push \
            --tag ${image_name}:${version} \ 
            --platform ${IMAGE_ARCH} .
          
          docker tag ${image_name}:${version} ${image_name}:latest
          
          docker push ${image_name}:latest
